fix: added pre push to husky to run test before pushing to github

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -17,3 +17,10 @@ fi
 echo "✅ Env check passed. Proceeding with push..."
 
 npm test
+
+if [ $? -ne 0 ]; then
+  echo "❌ Unit Tests Failed. Push aborted."
+  exit 1
+fi
+
+echo "✅ Test Passed. Proceeding with push..."
